from __future__ import annotations
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
APP = ROOT / "app.py"
TIMESERIES = ROOT / "epw_climate_analyzer" / "timeseries.py"
DOC = ROOT / "CLIMATE_CORE_0_7_4.md"
TEST = ROOT / "tests" / "test_time_series_styling_0_7_4_c2.py"

def replace_once(path: Path, old: str, new: str) -> None:
    text = path.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{path}: expected one anchor, found {count}: {old[:120]!r}")
    path.write_text(text.replace(old, new, 1), encoding="utf-8")

replace_once(TIMESERIES, '@dataclass(frozen=True)\nclass OverlaySeries:\n    label: str\n    column: str\n    unit: str\n    resolution: str\n\n    @property\n', '@dataclass(frozen=True)\nclass OverlaySeries:\n    label: str\n    column: str\n    unit: str\n    resolution: str\n    color: str | None = None\n    dash: str | None = None\n    width: float = 2.0\n    opacity: float = 1.0\n\n    @property\n')
replace_once(TIMESERIES, '        fig.add_trace(\n            go.Scatter(\n                x=x,\n                y=y,\n                mode="lines",\n                name=name,\n                yaxis=axis,\n                line={"color": metric_color(spec.column), "dash": dash_cycle[index % len(dash_cycle)]},\n                connectgaps=False,\n                hovertemplate=f"{name}<br>%{{x|%Y-%m-%d %H:%M}}<br>%{{y:.3g}} {spec.unit}<extra></extra>",\n            )\n        )\n', '        dash = spec.dash or dash_cycle[index % len(dash_cycle)]\n        if dash not in {"solid", "dash", "dot", "dashdot", "longdash", "longdashdot"}:\n            raise ValueError(f"Unsupported line dash style: {dash}")\n        width = float(spec.width)\n        opacity = float(spec.opacity)\n        if not np.isfinite(width) or width <= 0.0:\n            raise ValueError("Overlay line width must be a finite positive number.")\n        if not np.isfinite(opacity) or not 0.0 < opacity <= 1.0:\n            raise ValueError("Overlay opacity must be greater than 0 and at most 1.")\n        fig.add_trace(\n            go.Scatter(\n                x=x,\n                y=y,\n                mode="lines",\n                name=name,\n                yaxis=axis,\n                line={\n                    "color": spec.color or metric_color(spec.column),\n                    "dash": dash,\n                    "width": width,\n                },\n                opacity=opacity,\n                connectgaps=False,\n                hovertemplate=f"{name}<br>%{{x|%Y-%m-%d %H:%M}}<br>%{{y:.3g}} {spec.unit}<extra></extra>",\n            )\n        )\n')
replace_once(APP, '        resolution = col_resolution.selectbox(\n            f"Series {i + 1} resolution",\n            resolutions,\n            index=resolutions.index(default_resolution),\n            key=f"overlay_resolution_{i}",\n        )\n        column, unit = VARIABLES[variable_label]\n        specs.append(OverlaySeries(variable_label, column, unit, resolution))\n', '        resolution = col_resolution.selectbox(\n            f"Series {i + 1} resolution",\n            resolutions,\n            index=resolutions.index(default_resolution),\n            key=f"overlay_resolution_{i}",\n        )\n        column, unit = VARIABLES[variable_label]\n        style_labels = ["Solid", "Dashed", "Dotted", "Dash-dot"]\n        style_to_dash = {"Solid": "solid", "Dashed": "dash", "Dotted": "dot", "Dash-dot": "dashdot"}\n        with st.expander(f"Series {i + 1} style", expanded=False):\n            style_col1, style_col2, style_col3, style_col4 = st.columns([1.25, 1.0, 1.0, 1.0])\n            line_style = style_col1.selectbox(\n                "Line style",\n                style_labels,\n                index=i % len(style_labels),\n                key=f"overlay_line_style_{i}",\n            )\n            line_width = style_col2.slider(\n                "Line width",\n                min_value=0.5,\n                max_value=6.0,\n                value=2.0,\n                step=0.5,\n                key=f"overlay_line_width_{i}",\n            )\n            line_color = style_col3.color_picker(\n                "Line color",\n                value=metric_color(column),\n                key=f"overlay_line_color_{i}",\n            )\n            line_opacity = style_col4.slider(\n                "Opacity",\n                min_value=0.2,\n                max_value=1.0,\n                value=1.0,\n                step=0.05,\n                key=f"overlay_line_opacity_{i}",\n            )\n        specs.append(\n            OverlaySeries(\n                variable_label,\n                column,\n                unit,\n                resolution,\n                color=line_color,\n                dash=style_to_dash[line_style],\n                width=float(line_width),\n                opacity=float(line_opacity),\n            )\n        )\n')
replace_once(DOC, 'Implemented in C1:\n\n- Ground-temperature profile and animation views use one stable 12-month temperature domain and a wider fixed-height presentation.\n- Chronological multi-year ground calculations preserve real years through an explicit year selector; Calendar profile fits one clearly labelled climatological annual harmonic across represented years.\n- The selected-depth annual curve uses the same annual temperature range so seasonal damping with depth is visually comparable.\n- Liquid-precipitation heat maps are anchored at 0 mm with white for dry intervals and progressively stronger blue toward the observed maximum.\n- Precipitation duration/histogram/box/violin distributions default to **Wet intervals only**, with an explicit **All intervals including dry periods** option.\n\nStill planned for C:\n\n- Per-series Time Series and Overlay styling.\n- Sky & Daylight consolidation and removal of duplicated analysis routes.\n- Overview, humidity and natural-ventilation/HVAC duplicated-analysis cleanup.\n', 'Implemented in C1/C2:\n\n- Ground-temperature profile and animation views use one stable 12-month temperature domain and a wider fixed-height presentation.\n- Chronological multi-year ground calculations preserve real years through an explicit year selector; Calendar profile fits one clearly labelled climatological annual harmonic across represented years.\n- The selected-depth annual curve uses the same annual temperature range so seasonal damping with depth is visually comparable.\n- Liquid-precipitation heat maps are anchored at 0 mm with white for dry intervals and progressively stronger blue toward the observed maximum.\n- Precipitation duration/histogram/box/violin distributions default to **Wet intervals only**, with an explicit **All intervals including dry periods** option.\n- Every Time Series and Overlay series has independent line colour, style, width and opacity while retaining the existing common time axis, resolution semantics and two-unit-family limit.\n\nStill planned for C:\n\n- Sky & Daylight consolidation and removal of duplicated analysis routes.\n- Overview, humidity and natural-ventilation/HVAC duplicated-analysis cleanup.\n')

TEST.write_text('from __future__ import annotations\n\nfrom pathlib import Path\nimport unittest\n\nimport pandas as pd\n\nfrom epw_climate_analyzer.timeseries import OverlaySeries, build_overlay_figure\n\nROOT = Path(__file__).resolve().parents[1]\nAPP = ROOT / "app.py"\n\n\nclass TimeSeriesStyling074C2Tests(unittest.TestCase):\n    def _frame(self) -> pd.DataFrame:\n        index = pd.date_range("2026-01-01", periods=24, freq="h")\n        return pd.DataFrame(\n            {\n                "dry_bulb_temperature_c": [float(i) for i in range(24)],\n                "dew_point_temperature_c": [float(i) - 3.0 for i in range(24)],\n            },\n            index=index,\n        )\n\n    def test_explicit_series_style_reaches_plotly_trace(self) -> None:\n        frame = self._frame()\n        spec = OverlaySeries(\n            "Outdoor temperature",\n            "dry_bulb_temperature_c",\n            "°C",\n            "Native",\n            color="#123456",\n            dash="dashdot",\n            width=3.5,\n            opacity=0.55,\n        )\n        fig, _tables = build_overlay_figure(\n            frame,\n            [spec],\n            frame.index.min(),\n            frame.index.max() + pd.Timedelta(hours=1),\n        )\n        trace = fig.data[0]\n        self.assertEqual(trace.line.color, "#123456")\n        self.assertEqual(trace.line.dash, "dashdot")\n        self.assertEqual(float(trace.line.width), 3.5)\n        self.assertAlmostEqual(float(trace.opacity), 0.55)\n\n    def test_unstyled_series_keep_legacy_automatic_dash_cycle(self) -> None:\n        frame = self._frame()\n        specs = [\n            OverlaySeries("Dry bulb", "dry_bulb_temperature_c", "°C", "Native"),\n            OverlaySeries("Dew point", "dew_point_temperature_c", "°C", "Native"),\n        ]\n        fig, _tables = build_overlay_figure(\n            frame,\n            specs,\n            frame.index.min(),\n            frame.index.max() + pd.Timedelta(hours=1),\n        )\n        self.assertEqual(fig.data[0].line.dash, "solid")\n        self.assertEqual(fig.data[1].line.dash, "dash")\n\n    def test_ui_exposes_independent_style_controls_for_each_series(self) -> None:\n        source = APP.read_text(encoding="utf-8")\n        self.assertIn(\'f"Series {i + 1} style"\', source)\n        self.assertIn(\'"Line style"\', source)\n        self.assertIn(\'"Line width"\', source)\n        self.assertIn(\'"Line color"\', source)\n        self.assertIn(\'"Opacity"\', source)\n        self.assertIn(\'"Dash-dot"\', source)\n\n\nif __name__ == "__main__":\n    unittest.main()\n', encoding='utf-8')
print("0.7.4-C2 patch applied")
